main/views/basket_view.py
import flask
import datetime

import main.data.transactions.activity_db_transaction as adf
import main.data.transactions.user_db_transaction as udf
import main.data.transactions.transaction_db_transaction as tdf
from main.data.db_classes.transaction_db_class import Membership
import main.view_lib.cookie_lib as cl
import main.view_lib.basket_lib as bl

blueprint = flask.Blueprint("basket", __name__)


@blueprint.route("/misc/add_booking_to_basket", methods=["POST"])
def add_booking_to_basket_post():
    user, response, has_cookie = cl.return_user_response(flask.request, True)
    if response:
        return response

    data_form = flask.request.form
    activity = adf.return_activity_with_id(data_form.get('activity'))
    booking_amount: int = int(data_form.get("amount_of_people"))
    num_regular_sessions: int = int(data_form.get("num_regular_sessions"))

    if not activity or not booking_amount:
        flask.flash("Not checked out or booked activity", category="error")
        return flask.render_template("/misc/general_error.html", error="Not checked out or booked activity", has_cookie=has_cookie)

    is_valid, basket_activities, basket_membership, basket_membership_duration = \
        tdf.return_activities_and_memberships_from_basket_cookie_if_exists(flask.request)

    # TODO: Discuss if this is the desired behaviour
    #       In Test_4,Test_5, it's expected to render general_error page
    if not is_valid:
        flask.flash("User is invalid. Please try to login again.", category="error")
        return cl.destroy_account_cookie(flask.redirect("/account/login"))

    if basket_activities:
        if (basket_membership and (len(basket_activities) + booking_amount > 14)) or len(
                basket_activities) + booking_amount > 15:
            flask.flash("Basket full", category="error")
            return flask.render_template("/misc/general_error.html", error="Basket full", User=user, has_cookie=has_cookie)

    spaces_left = activity.session_type.maximum_activity_capacity - len(
        tdf.return_bookings_with_activity_id(activity.activity_id))
    if spaces_left <= 0:
        flask.flash("Not enough spaces left on activity", category="error")
        return flask.render_template("/misc/general_error.html", error="Not enough spaces left on activity",
                                     User=user, has_cookie=has_cookie)

    # Add all selected regular sessions to the basket cookie
    response = cl.add_activity_or_membership_to_basket(
        booking_objects=adf.return_regular_activities_from(activity, limit=num_regular_sessions),
        request=flask.request,
        num_people=booking_amount
    )

    if not response:
        return flask.abort(500)

    session_type = adf.return_session_type_with_id(activity.session_type_id)
    flask.flash(session_type.session_type_name.title()+" session has been added to your basket.", category="success")

    response.headers['Access-Control-Allow-Origin'] = '*'
    return response


@blueprint.route("/account/basket", methods=["GET"])
def basket_view():
    user, response, has_cookie = cl.return_user_response(flask.request, True)
    if response:
        return response

    is_valid, basket_activities, basket_membership, basket_membership_duration \
        = tdf.return_activities_and_memberships_from_basket_cookie_if_exists(flask.request)

    if basket_activities is None:
        basket_activities = list()

    if not is_valid:
        flask.flash("User is invalid. Please try to login again.", category="error")
        return cl.destroy_account_cookie(flask.redirect("/account/login"))

    # do not return if basket is empty
    if basket_activities is [] and (basket_membership is None or basket_membership_duration is None):
        return flask.render_template("/account/basket.html", User=user, has_cookie=has_cookie)

    new_activities_basket = ""
    redirect = False
    for activity in basket_activities:
        spaces_left = activity.session_type.maximum_activity_capacity - len(
            tdf.return_bookings_with_activity_id(activity.activity_id))
        number_of_activities = basket_activities.count(activity)
        if spaces_left >= number_of_activities and activity.start_time > datetime.datetime.now():
            if len(new_activities_basket) != 0:
                new_activities_basket += ";"
            new_activities_basket += "A:" + str(activity.activity_id)
        else:
            redirect = True

    if redirect:
        response = flask.redirect("/account/basket")
        response.set_cookie("vertex_basket_cookie", new_activities_basket, max_age=datetime.timedelta(days=1))
        return response

    regular_discounts = bl.return_regular_discounts(basket_activities)

    activity_and_price = dict()
    total_activity_price = 0
    for i, activity in enumerate(basket_activities):
        duration: datetime.timedelta = activity.end_time - activity.start_time
        current_price = (duration.seconds // 3600 * activity.session_type.hourly_activity_price)
        number_of_activities = basket_activities.count(activity)

        activity_and_price[activity] = (current_price, number_of_activities, regular_discounts[i])
        total_activity_price += current_price - (current_price * regular_discounts[i] / 100)  # TODO: Bad floating point for money

    current_membership_discount = 0
    memb_start_date = datetime.date.today()
    memb_end_date = None
    # total_discounted_price = 0  # can uncomment but this is not needed (why is python weird)
    if basket_membership:
        total_discounted_price = (total_activity_price - basket_membership.discount / 100 * total_activity_price)
        if memb_start_date.month+basket_membership_duration > 12:
            memb_end_date = datetime.date(memb_start_date.year+1, memb_start_date.month+basket_membership_duration-12, memb_start_date.day)
        elif memb_start_date.month+basket_membership_duration == 12:
            memb_end_date = datetime.date(memb_start_date.year + 1, memb_start_date.month, memb_start_date.day)
        else:
            memb_end_date = datetime.date(memb_start_date.year, memb_start_date.month+basket_membership_duration, memb_start_date.day)

        current_membership_discount = basket_membership.discount
        final_price = total_discounted_price + (basket_membership_duration * basket_membership.monthly_price)
    else:
        customer = udf.return_customer_with_user_id(user.user_id)
        if customer and customer.current_membership:
            customer_membership = Membership.query.filter_by(membership_id=customer.current_membership_id).first()

            total_discounted_price = total_activity_price - \
                                     customer_membership.membership_type.discount / 100 * total_activity_price
            current_membership_discount = customer_membership.membership_type.discount
            final_price = total_discounted_price
        else:
            total_discounted_price = total_activity_price
            final_price = total_activity_price

    return flask.render_template("/account/basket.html", basket_activities=basket_activities,
                                 basket_membership=basket_membership, User=user,
                                 total_activity_price=total_activity_price, has_cookie=has_cookie,
                                 activity_and_price=activity_and_price, final_price=round(final_price, 2),
                                 basket_membership_duration=basket_membership_duration,
                                 total_discounted_price=round(total_discounted_price, 2),
                                 current_membership_discount=current_membership_discount,
                                 membership_start_date=memb_start_date, membership_end_date=memb_end_date)


@blueprint.route("/account/basket", methods=["POST"])
def basket_delete_activity():
    user, response, has_cookie = cl.return_user_response(flask.request, True)
    if response:
        return response

    data_form = flask.request.form

    # if delete_all, create an empty basket cookie
    if data_form.get("delete_basket"):
        return cl.create_basket_cookie(flask.redirect("/account/basket"))

    # booking = data_form.get("update")
    booking_data = data_form.get("booking_id")
    num_change = int(data_form.get("num_change"))
    name = data_form.get("name")
    if booking_data is None or num_change > 8 or num_change < 0:
        return flask.abort(500)

    item = booking_data.split(":")
    if item[0] == "A":
        num_items = 2
        is_activity = True
    elif item[0] == "M":
        num_items = 3
        is_activity = False
    else:
        return flask.abort(500)

    if len(item) != num_items:
        return flask.abort(500)

    response = cl.change_items_with_id_from_cookie(item[1], num_change, flask.redirect("/account/basket"),
                                                   flask.request, is_activity=is_activity)

    if not response:
        flask.abort(500)

    flask.flash(f"Deleted {name}.", category="success")
    return response

main/views/info_view.py
import flask
import main.view_lib.cookie_lib as cl
import main.data.transactions.activity_db_transaction as adf
import main.data.transactions.transaction_db_transaction as tdf
from main.data.db_classes.activity_db_class import FacilityType
from main.data.db_classes.user_db_class import Customer
from main.data.db_classes.transaction_db_class import MembershipType
from main.data.db_session import add_to_database

blueprint = flask.Blueprint("info", __name__)


@blueprint.route('/info/about', methods=["GET"])
def about_func():
    user, response, has_cookie = cl.return_user_response(flask.request, False)
    print(adf.return_facility_types())
    return flask.render_template("/info/about.html", facility_types=adf.return_facility_types(), page_title="About", User=user, has_cookie=has_cookie)


@blueprint.route('/info/facilities', methods=["GET"])
def facilities_view():
    user, response, has_cookie = cl.return_user_response(flask.request, False)
    return flask.render_template("/info/facilities.html", has_cookie=has_cookie,
                                 facility_types=adf.return_facility_types(), page_title="Facilities", User=user)


@blueprint.route('/info/memberships', methods=["GET"])
def membership_view():
    user, response, has_cookie = cl.return_user_response(flask.request, False)
    standard_id = 1
    premium_id = 2
    standard_price = MembershipType.query.filter_by(membership_type_id=standard_id).first().monthly_price
    premium_price = MembershipType.query.filter_by(membership_type_id=premium_id).first().monthly_price

    return flask.render_template("/info/memberships.html", page_title="Memberships", has_cookie=has_cookie,
                                 User=user, premium_price=premium_price, standard_price=standard_price,
                                 standard_id=standard_id, premium_id=premium_id)


@blueprint.route("/info/memberships/buy", methods=["POST"])
def buy_membership():
    user, response, has_cookie = cl.return_user_response(flask.request, True)
    if response:
        return response

    membership_id = int(flask.request.form.get('buy_membership'))
    membership_duration = int(flask.request.form.get('membership_duration'))
    if membership_id is None:
        return flask.redirect("/info/memberships")

    is_valid, basket_activities, basket_membership, basket_membership_duration = \
        tdf.return_activities_and_memberships_from_basket_cookie_if_exists(flask.request)

    if not is_valid:
        flask.flash("User is invalid. Please try to login again.", category="error")
        return cl.destroy_account_cookie(flask.redirect("/account/login"))

    new_membership_type = tdf.return_membership_type_with_id(membership_id)
    response = cl.add_activity_or_membership_to_basket(
        new_membership_type, flask.request, duration=membership_duration)

    membership_type = MembershipType.query.filter_by(membership_type_id=membership_id).first().name
    flask.flash(membership_type.title() + " Membership has been added to your basket.", category="success")
    return response


@blueprint.route("/info/memberships/cancel", methods=["GET"])
def cancel_membership():
    user, response, has_cookie = cl.return_user_response(flask.request, True)
    if response:
        return response

    if type(user) is Customer:
        customer = Customer.query.filter_by(user_id=user.user_id).first()
        customer.current_membership = None
        add_to_database(customer)

    return flask.redirect("/account/membership")

main/templates/includes/_main_layout.html
<!-- This html document defines the format that is followed by all the other
pages, making it the parent page. This defines the head of the document as well
as the basic body -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Team 10">
    <meta name="keywords" content="Leisure centre, Gym, Swimming, Activities, Membership, Fitness">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title> <!-- Lets each page have its own title-->
    <!--  Import font  -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900|Open+Sans:300,400,500&display=swap"
          rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/includes/reset.css') }}">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/includes/global.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/includes/main.css') }}">
    <link rel="icon" href="../static/imgs/logo/vertex_favicon.png" type="image/ico" sizes="16x16">
    {% block additional_css %}{% endblock %} <!--Allows extra css to be added-->
</head>
<body>

{% if has_cookie == False %}
<div id="cookies"> <!-- Defines the div for displaying cookie information-->
    <h2>We love cookies!</h2>
    <p>Our website uses cookies; these are vital for storing your account details and making
        sure that you can use the website as intended. Don't worry- we're not out to get you!
        Please accept below:</p>
    <a class="btn-success" id="CookieAccept">Accept!</a>
</div>
<div id="invisible"></div>
{% endif %}

{% if not nav %} <!-- Inspired from: https://mdbootstrap.com/docs/jquery/navigation/navs/-->
<nav class="navbar navbar-expand-lg navbar-light main-nav" id="main-nav">
<!--    <div class="container justify-content-center">-->
    <div class="d-block d-lg-none mx-auto" id="brand-mobile">
        <a class="navbar-brand" base href="/"><img src="../static/imgs/logo/vertex_logo.png"></a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav flex-fill w-100 flex-nowrap" id="nav-content-left">
            <li class="nav-item">
               <a class="nav-link" base href="{{ url_for('activities.view_activity_types')}}">Activities</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" base href="{{ url_for('info.facilities_view')}}">Facilities</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" base href="{{ url_for('info.membership_view')}}">Membership</a>
            </li>
        </ul>
        <ul class="nav navbar-nav flex-fill justify-content-center d-none d-lg-block">
            <li class="nav-item">
                <a class="navbar-brand mx-auto" base href="/"><img src="../static/imgs/logo/vertex_logo.png"></a>
            </li>
        </ul>
        <ul class="nav navbar-nav flex-fill w-100 justify-content-end" id="nav-content-right">
            <li class="nav-item"><a class="nav-link" base href="{{ url_for('info.about_func')}}">About</a></li>
            {% if not User %}
            <!--            <li class="nav-item"><a class="nav-link" base href="/account/log_out">Logout</a></li>-->
            <li class="nav-item navbar-right"><a class="nav-link glyphicon glyphicon-log-out" base
                                                 href="{{ url_for('account.register_get')}}">Register</a></li>
            <li class="nav-item navbar-right"><a class="nav-link glyphicon glyphicon-log-in" base
                                                 href="{{ url_for('account.login_get')}}">Login</a></li>
            {% else %}
            <li class="nav-item d-block d-lg-none"><a class="nav-link" href="{{ url_for('account.view_account')}}">Account</a></li>
            <li class="nav-item dropdown d-none d-lg-block">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a href="{{ url_for('account.view_account')}}" class="nav-link pl-0">
                        <p>Home</p></a>
                    <a href="{{ url_for('account.view_account_bookings')}}" class="nav-link pl-0">
                        <p>Bookings</p></a>
                    <a href="{{ url_for('account.view_account_receipts')}}" class="nav-link pl-0">
                        <p>Receipts</p></a>
                    {% if User.__mapper_args__['polymorphic_identity'] == "Customer" %}
                    <a href="{{ url_for('account.view_account_membership')}}" class="nav-link pl-0">
                        <p>Membership</p></a>
                    {% elif User.__mapper_args__['polymorphic_identity'] == "Employee" %}
                    {% elif User.__mapper_args__['polymorphic_identity'] == "Manager" %}
                    <a href="{{ url_for('account.view_usages')}}" class="nav-link pl-0">
                        <p>Statistics</p></a>
                    {% endif %}
                    <a href="{{ url_for('account.view_account_details')}}" class="nav-link pl-0">
                        <p>Account</p></a>
                    {% if User.__mapper_args__['polymorphic_identity'] == "Customer" %}
                    <a href="{{ url_for('account.view_payment_details')}}" class="nav-link pl-0">
                        <p>Card Details</p></a>
                    {% elif User.__mapper_args__['polymorphic_identity'] == "Employee" or
                    User.__mapper_args__['polymorphic_identity'] == "Manager" %}
                    <a href="#" class="nav-link pl-0">
                        <p>Rota</p></a>
                    {% endif %}
                    <a href="{{ url_for('account.log_out')}}" class="nav-link pl-0">
                        <p>Log Out</p></a>
                </div>
            </li>
            <li class="nav-item navbar-right">
                <a class="nav-link glyphicon glyphicon-shopping-cart" base href="{{ url_for('basket.basket_view')}}">Basket</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endif %}
{% if page_title is defined %} <!-- Page title is not empty -->
<div id="page_title" class="fluid-container">
    <div class="container">
        <div class="row">
            <h1 class="align-self-center col-12 col-lg-4">{{ page_title }}</h1>
            <span id="page_description" class="align-self-center col-12 col-lg-8">
                {% block page_description %} {% endblock %}
            </span>
        </div>
    </div>
</div>
{% endif %}

<!--Defines the main content for the webpages, this is where allthe content is situated-->
{% block main_content %} {% endblock %}

{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
{% for message in messages %}
{% if message[0] == ("success") %}
<div class="alert alert-success fade show" role="alert">
    {% elif message[0] == ("error") %}
    <div class="alert alert-danger fade show" role="alert">
        {% else %}
        <div class="alert alert-primary fade show" role="alert">
            {% endif %}
            {{ message[1] }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
</div>

    {% if footer == True %} <!-- Inspired from: https://mdbootstrap.com/docs/jquery/navigation/footer/-->
    <footer>
    </footer>
    {% endif %}

    <!-- Imports CDNs for scripts that are used by every page, most importantly bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/c8eac23e18.js" crossorigin="anonymous"></script>
    <script src="../../static/js/main.js">

    </script>
    {% block additional_js %} {% endblock %} <!--Lets the user input additional JavaScript -->
</body>
</html>